<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<groupId>demo.fuse</groupId>
	<artifactId>common-services</artifactId>
	<version>1.0.0</version>
	<name>Demo - common-services</name>
	<packaging>bundle</packaging>
	<properties>
		<camel.version>2.23.2</camel.version>
		<commons.lang.version>2.6</commons.lang.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.apache.camel</groupId>
			<artifactId>camel-core</artifactId>
			<version>${camel.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>2.3.7</version>
				<extensions>true</extensions>
			</plugin>
		</plugins>
	</build>
</project>
