"""initial_schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_project_id'), ['project_id'], unique=False)

    op.create_table('idempotency_record',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('endpoint', sa.String(length=300), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('actor', 'key')
    )
    op.create_table('organization',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_published_at'), ['published_at'], unique=False)

    op.create_table('repository',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('credential_ref', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_catalog',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('source_uri', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('target_profile',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('runtime', sa.String(length=20), nullable=False),
    sa.Column('java_version', sa.String(length=10), nullable=False),
    sa.Column('camel_version', sa.String(length=30), nullable=False),
    sa.Column('runtime_version', sa.String(length=30), nullable=False),
    sa.Column('bom_coordinates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tooling', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dependency_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version')
    )
    op.create_table('project',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('target_runtime', sa.String(length=20), nullable=True),
    sa.Column('required_gates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('independent_review', sa.Boolean(), nullable=False),
    sa.Column('pr_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name')
    )
    op.create_table('artifact',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_project_id'), ['project_id'], unique=False)

    op.create_table('job',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=200), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_state_lease', ['state', 'lease_until'], unique=False)

    op.create_table('membership',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'subject_id')
    )
    op.create_table('scan',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('catalog_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('maven_resolution', sa.String(length=30), nullable=False),
    sa.Column('maven_resolution_detail', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['rule_catalog.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.create_index('ix_scan_project_created', ['project_id', 'created_at'], unique=False)

    op.create_table('finding',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=1200), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=1000), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'fingerprint')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_finding_scan_status_sev', ['scan_id', 'status', 'severity'], unique=False)

    op.create_table('job_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_event_job_id'), ['job_id'], unique=False)

    op.create_table('module',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('artifact_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('packaging', sa.String(length=30), nullable=False),
    sa.Column('java_observed', sa.String(length=40), nullable=True),
    sa.Column('java_resolved', sa.String(length=40), nullable=True),
    sa.Column('java_source', sa.String(length=100), nullable=True),
    sa.Column('camel_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=False),
    sa.Column('unresolved', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dependencies', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('profiles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_scan_id'), ['scan_id'], unique=False)

    op.create_table('plan',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['target_profile.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'version')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_project_id'), ['project_id'], unique=False)

    op.create_table('route',
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('route_key', sa.String(length=1100), nullable=False),
    sa.Column('route_id', sa.String(length=255), nullable=True),
    sa.Column('dsl', sa.String(length=10), nullable=False),
    sa.Column('file', sa.String(length=1000), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('detection', sa.String(length=40), nullable=False),
    sa.Column('from_uri', sa.Text(), nullable=True),
    sa.Column('dynamic_from', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_scan_id'), ['scan_id'], unique=False)

    op.create_table('endpoint',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=True),
    sa.Column('redacted_uri', sa.Text(), nullable=True),
    sa.Column('dynamic', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_endpoint_route_id'), ['route_id'], unique=False)

    op.create_table('execution',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('candidate_sha', sa.String(length=64), nullable=True),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('pr_url', sa.String(length=1000), nullable=True),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_project_id'), ['project_id'], unique=False)

    op.create_table('finding_review',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_review_finding_id'), ['finding_id'], unique=False)

    op.create_table('plan_step',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('gate', sa.String(length=5), nullable=True),
    sa.Column('recipe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('preconditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('finding_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('depends_on', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rollback', sa.Text(), nullable=False),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_step_plan_id'), ['plan_id'], unique=False)

    op.create_table('diff_file',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('change_type', sa.String(length=10), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('recipes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('patch', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=10), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diff_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diff_file_execution_id'), ['execution_id'], unique=False)

    op.create_table('validation',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('suite', sa.String(length=30), nullable=False),
    sa.Column('target', sa.String(length=10), nullable=False),
    sa.Column('gate', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_execution_id'), ['execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_execution_id'))

    op.drop_table('validation')
    with op.batch_alter_table('diff_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diff_file_execution_id'))

    op.drop_table('diff_file')
    with op.batch_alter_table('plan_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_step_plan_id'))

    op.drop_table('plan_step')
    with op.batch_alter_table('finding_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_review_finding_id'))

    op.drop_table('finding_review')
    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_project_id'))
        batch_op.drop_index(batch_op.f('ix_execution_plan_id'))

    op.drop_table('execution')
    with op.batch_alter_table('endpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoint_route_id'))

    op.drop_table('endpoint')
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_scan_id'))

    op.drop_table('route')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_project_id'))

    op.drop_table('plan')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_scan_id'))

    op.drop_table('module')
    with op.batch_alter_table('job_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_event_job_id'))

    op.drop_table('job_event')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index('ix_finding_scan_status_sev')
        batch_op.drop_index(batch_op.f('ix_finding_project_id'))

    op.drop_table('finding')
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_project_created')

    op.drop_table('scan')
    op.drop_table('membership')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_state_lease')

    op.drop_table('job')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_project_id'))

    op.drop_table('artifact')
    op.drop_table('project')
    op.drop_table('target_profile')
    op.drop_table('rule_catalog')
    op.drop_table('repository')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_published_at'))

    op.drop_table('outbox')
    op.drop_table('organization')
    op.drop_table('idempotency_record')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_at'))

    op.drop_table('audit_event')
    op.drop_table('app_user')
    # ### end Alembic commands ###
