"""source_types_and_snapshots

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('structure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_owner'), ['owner'], unique=False)

    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_snapshot', sa.String(length=64), nullable=True))
        batch_op.alter_column('base_sha',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(length=10), nullable=False, server_default='git'))
        batch_op.add_column(sa.Column('local_path', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('upload_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('snapshot_artifact_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('project_root', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('project_root')
        batch_op.drop_column('snapshot_artifact_id')
        batch_op.drop_column('snapshot_hash')

    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('upload_id')
        batch_op.drop_column('local_path')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('execution', schema=None) as batch_op:
        batch_op.alter_column('base_sha',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('base_snapshot')

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_owner'))

    op.drop_table('upload')
    # ### end Alembic commands ###
