"""effort_log

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effort_log',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('effort_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_effort_log_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_effort_log_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('effort_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_effort_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_effort_log_category'))

    op.drop_table('effort_log')
    # ### end Alembic commands ###
