"""workspace_retry

Revision ID: 0007
Revises: 0006
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_migration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_of', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('retry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_migration', schema=None) as batch_op:
        batch_op.drop_column('retry')
        batch_op.drop_column('retry_of')

    # ### end Alembic commands ###
